### PR TITLE
Fix for relationship mutations are not using the correct direction

### LINKED ISSUE #98: Relationship mutations are not using the correct direction
I have a database with nodes like this:

graph

And a graphql schema like this:

```
type Team {
  id: ID!
  name: String!
  players: [Player!]! @relation(name: "MEMBER_OF", direction: IN)
}

type Player {
  id: ID!
  name: String!
  teams: [Team] @relation(name: "MEMBER_OF")
}
```

The cypher queries generated when I run the deleteTeamPlayers and addTeamPlayers mutations are specifying the relationship in the wrong direction.

Here's the cypher generated by deleteTeamPlayers:

> RUN "MATCH (from:Team { id: $fromId }) MATCH (to:Player) WHERE  to.id IN $toPlayers **MATCH (from)-[r:MEMBER_OF]->(to)** DELETE r WITH DISTINCT from AS deleteResult RETURN deleteResult { .name } AS deleteResult"

And here's addTeamPlayers:

> RUN "MATCH (from:Team { id: $fromId }) MATCH (to:Player) WHERE  to.id IN $toPlayers **MERGE (from)-[:MEMBER_OF]->(to)** WITH DISTINCT from AS addResult RETURN addResult { .name } AS addResult"

These queries are building MATCH and MERGE clauses going from Team to Player even though my graphQL schema and database have the relationships going from Player to Team. The result is that the deleteTeamPlayers mutation doesn't do anything since it can't find any relationships to match on, and the addTeamPlayers mutation adds a relationship in the opposite direction of what's desired.

The deletePlayerTeams and addPlayerTeams mutations that were generated from the Player type work fine. It seems like the problem is that these relationship mutations are always using an outbound direction.

### PR DESCRIPTION
**Pull request by Andy2003**
This bugfix solves the problem that the mapping was wrong for incoming relations

(resolves #98)

### CODE REVIEW

File: src/main/kotlin/org/neo4j/graphql/GraphQLExtensions.kt [hunk 1]
```diff
@@ -49,9 +49,13 @@ fun GraphQLFieldsContainer.relationshipFor(name: String): RelationshipInfo? {
...
     val fieldObjectType = field.type.inner() as? GraphQLFieldsContainer ?: return null
 
-    val (relDirective, isRelFromType) = if (isRelationType()) {
+    val (relDirective, inverse) = if (isRelationType()) {
+        val typeName = this.name
         (this as? GraphQLDirectiveContainer)
-            ?.getDirective(DirectiveConstants.RELATION)?.let { it to false }
+            ?.getDirective(DirectiveConstants.RELATION)?.let {
+                // do inverse mapping, if the current type  is the `to` mapping of the relation
+                it to (fieldObjectType.getFieldDefinition(it.getArgument(RELATION_TO, null))?.name == typeName)
```
Comment (jexp) [inline src/main/kotlin/org/neo4j/graphql/GraphQLExtensions.kt:57]: we need to be careful, this doesn't always work. if you have a rich relationship which has the same type in to/from then we need to use the explicit information from that type.

Comment (jexp) [reply src/main/kotlin/org/neo4j/graphql/GraphQLExtensions.kt:57]: we need the information the rel-field then I mean that indicates the correct direction otherwise it's "random" if from/to is matching the type name.

File: src/main/kotlin/org/neo4j/graphql/GraphQLExtensions.kt [hunk 2]
```diff
@@ -49,9 +49,13 @@ fun GraphQLFieldsContainer.relationshipFor(name: String): RelationshipInfo? {
             ?: throw IllegalArgumentException("$name is not defined on ${this.name}")
     val fieldObjectType = field.type.inner() as? GraphQLFieldsContainer ?: return null
 
-    val (relDirective, isRelFromType) = if (isRelationType()) {
+    val (relDirective, inverse) = if (isRelationType()) {
```
Comment (jexp) [inline src/main/kotlin/org/neo4j/graphql/GraphQLExtensions.kt:52]: perhaps we can simplify this code a bit so it gets easier to understand.

File: src/main/kotlin/org/neo4j/graphql/GraphQLExtensions.kt (hunk 1 above)
Comment (jexp) [reply src/main/kotlin/org/neo4j/graphql/GraphQLExtensions.kt:57]: see: https://github.com/neo4j-graphql/neo4j-graphql-java/issues/45

File: src/main/kotlin/org/neo4j/graphql/GraphQLExtensions.kt [hunk 3]
```diff
@@ -60,11 +64,8 @@ fun GraphQLFieldsContainer.relationshipFor(name: String): RelationshipInfo? {
                 ?: throw IllegalStateException("Field $field needs an @relation directive")
     }
 
-    // TODO direction is depending on source/target type
-
-    val relInfo = relDetails(fieldObjectType) { argName, defaultValue -> relDirective.getArgument(argName, defaultValue) }
+    val relInfo = relDetails(fieldObjectType, relDirective)
 
-    val inverse = isRelFromType && fieldObjectType.getFieldDefinition(relInfo.startField)?.name != this.name
```
Comment (jexp) [inline src/main/kotlin/org/neo4j/graphql/GraphQLExtensions.kt:67]: where is this bit handled now?

Comment (jexp) [reply src/main/kotlin/org/neo4j/graphql/GraphQLExtensions.kt:67]: this was the fix for issue #45

Comment (Andy2003) [reply src/main/kotlin/org/neo4j/graphql/GraphQLExtensions.kt:67]: I moved it to https://github.com/Andy2003/neo4j-graphql-java/blob/bugfix/%2398-fix-relationship-mapping/src/main/kotlin/org/neo4j/graphql/GraphQLExtensions.kt#L57 since it is only relevant for rich relations

File: src/test/resources/relationship-tests.adoc [hunk 4]
```diff
@@ -0,0 +1,323 @@
+:toc:
+
+= Movie Test TCK
```
Comment (greg-katz) [inline src/test/resources/relationship-tests.adoc:3]: Should this be `Relationship Test TCK` rather than `Movie Test TCK`?

Comment (jexp) [reply src/test/resources/relationship-tests.adoc:3]: Thanks for spotting this, fixed in master.
